---
# Configure apt proxy settings
- hosts: localhost
  connection: local
  tasks:
  - name: Deploy the proxydetect script
    copy:
      src: files/bin/proydetect
      dest: /usr/local/bin/proxydetect
      mode: "0755"
      owner: root
      group: root

  - name: Deploy the autoproxy config
    template:
      src: apt/apt.conf.d/30autoproxy.j2
      dest: /etc/apt/apt.conf.2/30autoproxy
      owner: root
      group: root
      mode: "0644"
