# Bazelisk CLI
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Get the latest Bazelisk release
    set_fact:
      bazelisk_releases: |
        {{ query("github_releases", user="bazelbuild", repo="bazelisk", latest=1)[0] }}

  - name: Get the current Bazelisk version
    set_fact:
      bazelisk_version: "{{ bazelisk_releases.in_order[0]['tag_name'].lstrip('v') }}"

  - name: Get current Bazelisk names
    set_fact:
      bazelisk_download_name: bazelisk_amd64.deb
      bazelisk_install_path: "{{ user_dirs.opt }}/bazelisk"

  - name: Gather the package facts
    package_facts:
      manager: auto

  - name: Install package directly
    apt:
      deb: "{{bazelisk_releases.asset_by_tag[bazelisk_version][bazelisk_download_name].browser_download_url}}"
    when: packages["bazelisk"][0]["version"]|default("") != bazelisk_version 