---
# Bubblewrap fixes
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install apparmor profile for bubblewrap
    copy:
      content: |
        abi <abi/4.0>,
        include <tunables/global>

        profile bwrap /usr/bin/bwrap flags=(unconfined) {
          userns,

          # Site-specific additions and overrides. See local/README for details.
          include if exists <local/bwrap>
        }
      dest: /etc/apparmor.d/bwrap
    notify: restart apparmor
  handlers:
  - name: restart apparmor
    service:
      name: apparmor
      state: restarted