# Install Clang 18
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Download Clang Key
    get_url:
      url: https://apt.llvm.org/llvm-snapshot.gpg.key
      dest: "{{apt_keyring_dir}}/llvm-snapshot.gpg.key"

  - name: Add Clang Repo
    apt_repository:
      filename: llvm-snapshot
      repo: "{{item}}"
    loop:
    - deb [arch=amd64 signed-by={{apt_keyring_dir}}/llvm-snapshot.gpg.key] http://apt.llvm.org/{{ansible_distribution_release}}/ llvm-toolchain-{{ansible_distribution_release}}-18 main
    - deb-src [arch=amd64 signed-by={{apt_keyring_dir}}/llvm-snapshot.gpg.key] http://apt.llvm.org/{{ansible_distribution_release}}/ llvm-toolchain-{{ansible_distribution_release}}-18 main

  - name: Install packages 
    package:
      name:
        # LLVM
      - libllvm-18-ocaml-dev
      - libllvm18
      - llvm-18
      - llvm-18-dev
      - llvm-18-doc
      - llvm-18-examples
      - llvm-18-runtime
      # Clang and co
      - clang-18
      - clang-tools-18
      - clang-18-doc
      - libclang-common-18-dev
      - libclang-18-dev
      - libclang1-18
      - clang-format-18
      - python3-clang-18
      - clangd-18
      - clang-tidy-18
      # compiler-rt
      - libclang-rt-18-dev
      # polly
      - libpolly-18-dev
      # libfuzzer
      - libfuzzer-18-dev
      # lldb
      - lldb-18
      # lld (linker)
      - lld-18
      # libc++
      - libc++-18-dev
      - libc++abi-18-dev
      # OpenMP
      - libomp-18-dev
      # libclc
      - libclc-18-dev
      # libunwind
      - libunwind-18-dev
      # mlir
      - libmlir-18-dev
      - mlir-18-tools
      # bolt
      - libbolt-18-dev
      - bolt-18
      # flang
      - flang-18
      # wasm support
      - libclang-rt-18-dev-wasm32
      - libclang-rt-18-dev-wasm64
      - libc++-18-dev-wasm32
      - libc++abi-18-dev-wasm32
      - libclang-rt-18-dev-wasm32
      - libclang-rt-18-dev-wasm64
