# Install Clang 18
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Download Clang Key
    get_url:
      url: https://apt.llvm.org/llvm-snapshot.gpg.key
      dest: "{{apt_keyring_dir}}/llvm-snapshot.gpg.key"

  - name: Add Clang Repo
    apt_repository:
      filename: llvm-snapshot
      repo: "{{item}}"
    loop:
    - deb [arch=amd64 signed-by={{apt_keyring_dir}}/llvm-snapshot.gpg.key] http://apt.llvm.org/{{ansible_distribution_release}}/ llvm-toolchain-{{ansible_distribution_release}}-18 main
    - deb-src [arch=amd64 signed-by={{apt_keyring_dir}}/llvm-snapshot.gpg.key] http://apt.llvm.org/{{ansible_distribution_release}}/ llvm-toolchain-{{ansible_distribution_release}}-18 main

  - name: Install packages 
    package:
      name:
        # LLVM
      - libllvm-{{item}}-ocaml-dev
      - libllvm{{item}}
      - llvm-{{item}}
      - llvm-{{item}}-dev
      - llvm-{{item}}-doc
      - llvm-{{item}}-examples
      - llvm-{{item}}-runtime
      # Clang and co
      - clang-{{item}}
      - clang-tools-{{item}}
      - clang-{{item}}-doc
      - libclang-common-{{item}}-dev
      - libclang-{{item}}-dev
      - libclang1-{{item}}
      - clang-format-{{item}}
      - python3-clang-{{item}}
      - clangd-{{item}}
      - clang-tidy-{{item}}
      # compiler-rt
      - libclang-rt-{{item}}-dev
      # polly
      - libpolly-{{item}}-dev
      # libfuzzer
      - libfuzzer-{{item}}-dev
      # lldb
      - lldb-{{item}}
      # lld (linker)
      - lld-{{item}}
      # libc++
      - libc++-{{item}}-dev
      - libc++abi-{{item}}-dev
      # OpenMP
      - libomp-{{item}}-dev
      # libclc
      - libclc-{{item}}-dev
      # libunwind
      - libunwind-{{item}}-dev
      # mlir
      - libmlir-{{item}}-dev
      - mlir-{{item}}-tools
      # bolt
      - libbolt-{{item}}-dev
      - bolt-{{item}}
      # flang
      - flang-{{item}}
      # wasm support
      - libclang-rt-{{item}}-dev-wasm32
      - libclang-rt-{{item}}-dev-wasm64
      - libc++-{{item}}-dev-wasm32
      - libc++abi-{{item}}-dev-wasm32
      - libclang-rt-{{item}}-dev-wasm32
      - libclang-rt-{{item}}-dev-wasm64
    loop:
    - 18
