---
# General system configuration which doesn't fit elsewhere
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Deploy configuration templates
    template:
      src: etc/default/localnetwork.j2
      dest: /etc/default/localnetwork
      owner: root
      group: root
      mode: "0644"
  
  - name: Set inotify user watches
    sysctl: 
      name: fs.inotify.max_user_watches
      value: '2097152'
      state: present
  
- hosts: localhost
  connection: local
  become: false
  tasks:
  - name: Ensure the user config dir exists
    block:
    - file:
        path: "{{ home_dir }}/config"
        state: directory
    
    - file:
        path: "{{ home_dir }}/config/linux"
        state: directory

    - file:
        path: "{{ home_dir }}/config/linux/shared"
        state: directory
  
  - name: Ensure user config bashrc loads
    lineinfile:
      path: "{{ home_dir }}/.bashrc"
      regexp: ^source $HOME/config/linux/shared/bashrc
      line: source $HOME/config/linux/shared/bashrc
