# Restore the cinnamon dconf settings backup made by pull.yml
- hosts: localhost
  connection: local
  vars:
    dconf_backup_file: "{{ [persistent_user_config.linux.shared, dconf_backup_files.cinnamon] | path_join }}"
  tasks:
  # The settings arrive via syncthing, so won't exist on a fresh machine.
  - name: Check for dconf settings
    stat:
      path: "{{ dconf_backup_file }}"
    register: dconf_settings

  - name: Restoring dconf settings
    shell: dconf load / < {{ dconf_backup_file }}
    when: dconf_settings.stat.exists
