- hosts: localhost
  connection: local
  tasks:
  # The settings arrive via syncthing, so won't exist on a fresh machine.
  - name: Check for dconf settings
    stat:
      path: "{{persistent_user_config.linux.shared}}/dconf.settings"
    register: dconf_settings

  - name: Restoring dconf settings
    shell: dconf load / < {{persistent_user_config.linux.shared}}/dconf.settings
    when: dconf_settings.stat.exists
