---
# Install docker-compose
- hosts: localhost
  connection: local
  become: true
  tasks:
  - file:
      path: /usr/local/bin
      state: directory
      owner: root
      group: root
      mode: "0755"
  - get_url:
      url: https://github.com/docker/compose/releases/download/v2.32.4/docker-compose-linux-x86_64 
      dest: /usr/local/bin/docker-compose
      owner: root
      group: root
      mode: "0755"