---
# FreeCad Menu Setup
- hosts: localhost
  connection: local
  become: false
  tasks:
  - file:
      src: "{{ user_dirs.opt }}/freecad/org.freecad.FreeCAD.desktop"
      dest: "{{ home_dir }}/.local/share/applications/org.freecad.FreeCAD.desktop"
      state: link
      force: true
