# Deploy/update a personal computer system.
- hosts: localhost
  connection: local
  tasks:
  - name: GTK3 theme customizations
    copy:
      src: "{{ files_dir }}/home/.config/gtk-3.0/gtk.css"
      dest: >-
        {{ [ home_dir, ".config", "gtk-3.0", "gtk.css" ] | path_join }}
      remote_src: true