# Kubernetes CLI
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Download K8S Deb Key
    get_url:
      url: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key"
      dest: "{{apt_keyring_dir}}/kubernetes-apt-keyring.key"

  - name: Install K8S repository
    apt_repository:
      filename: k8s
      repo: >
        deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.key] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /

  - name: Install K8S tools
    package:
      name:
        - kubectl
