---
# Basic system packages. This produces a functional command line, it would be applicable everywhere.
- hosts: localhost
  connection: local
  become: true
  tasks:
  - package:
      name:
      - apt-transport-https
      - ca-certificates
      - ca-certificates-java
      - dnsutils
      - net-tools
      - xmlstarlet
      - tcpdump
      - build-essential
      - connect-proxy
      - corkscrew
      - ssh
      - git
      - nano
      - openssl
      - parted
      - pv
      - pwgen
      - gpg2
      - socat
      - tcpdump
      - tsocks
      - util-linux
      - xxd
      - gzip
      - xz-utils
      - libnss3-tools
      - etherwake
      state: latest

# Boot packages
- hosts: localhost
  connection: local
  become: true
  tasks:
  - package:
      name:
      - clevis
      - clevis-initramfs
      - clevis-luks
      - clevis-systemd
      - clevis-tpm
      - clevis-udisks2
      state: latest

# Desktop packages. This produces a functional desktop and would be applicable everywhere.
- hosts: localhost
  connection: local
  become: true
  tasks:
  - package:
      name:
      - cinnamon-session
      - nemo
      - nemo-compare
      - nemo-gtkhash
      - nemo-fileroller
      - nemo-python
      - nemo-share
      - nemo-mediainfo-tab
      - dconf-cli
      - dconf-editor
      - libreoffice
      - gimp
      - audacity
      - default-jdk
      - lnav
      - cloud-guest-utils
      - gparted
      - graphviz
      - dhcping
      - htop
      - iotop
      - opensnitch
      - ovmf
      - p11-kit
      - p11-kit-modules
      - rclone
      - ssh-askpass-gnome
      - sysstat
      - wireshark
      - v4l-utils
      - xclip
      - xsel
      - xdot
      - git-gui

      state: latest

# Personalization packages - the applications I use.
- hosts: localhost
  connection: local
  become: true
  tasks:
  - package:
      name:
      - calibre
      - blender
      - dosbox
      - imagemagick
      - openshot
      - samba
      - shotwell
      - shutter
      - xournal
      - zeal
      # Serial comm package
      - tio
      - kicad
      - kicad-templates
      - kicad-libraries
      - kicad-footprints
      - kicad-symbols
      - kicad-packages3d
      - sigrok
      - netperf
      - flent
      state: latest

# Build Packages - things I've added
- hosts: localhost
  connection: local
  become: true
  tasks:
  - package:
      name:
      - python3
      - python3-venv
      - cmake
      - ninja
      - libopenmpi-dev
      - libstdc++-14-dev
      state: latest
