---
# Pull local settings into the repository for normalization.
- hosts: localhost
  connection: local
  tasks:
  - name: Collect dconf configuration
    shell: dconf dump / > {{files_dir}}/dconf.settings
