---
# Rust Config
- hosts: localhost
  connection: local
  become: false
  vars:
    rustup_download_url: https://sh.rustup.rs
    rustup_download_path: "{{ [ user_dirs.bin, 'rustup.sh' ] | path_join }}"
    installed_rustup: "{{ [ home_dir, '.cargo', 'bin', 'rustup' ] | path_join }}"
  tasks:
  - name: Download RustUp
    get_url:
      url: "{{ rustup_download_url }}"
      dest: "{{ rustup_download_path }}"
      mode: "0755"

  - name: Check if rustup is in the path
    shell: command -v rustup
    register: rustup_present
    ignore_errors: true

  - name: Install Rust if Needed
    command: rustup.sh -y --profile=default --default-toolchain=nightly
    when: rustup_present.failed|default(False)

  - name: Ensure nightly
    command: "{{installed_rustup}} toolchain install nightly"

  - name: Switch to nightly
    command: "{{installed_rustup}} default nightly"