---
# Rust Config
- hosts: localhost
  connection: local
  become: false
  vars:
    rustup_download_url: https://sh.rustup.rs
    rustup_download_path: "{{ [ user_dirs.bin, 'rustup.sh' ] | path_join }}"
    installed_rustup: "{{ [ home_dir, '.cargo', 'bin', 'rustup' ] | path_join }}"
  tasks:
  - name: Ensure cargo is in PATH
    lineinfile:
      path: '{{ [home_dir,".bashrc"]|path_join }}'
      line: export PATH=$PATH:{{[ home_dir, '.cargo', 'bin'] | path_join}}

  - name: Download RustUp
    get_url:
      url: "{{ rustup_download_url }}"
      dest: "{{ rustup_download_path }}"
      mode: "0755"

  - name: Check if rustup is in the path
    stat:
      path: "{{installed_rustup}}"
    register: rustup_present
    ignore_errors: true

  - name: Install Rust if Needed
    shell: 
      cmd: rustup.sh -y --profile=default --default-toolchain=nightly
    when: (not rustup_present.stat.exists)|default(True)

  - name: Ensure nightly
    shell: |
      {{home_dir}}/.cargo/bin/rustup toolchain install nightly
    args:
      executable: /bin/bash

  - name: Switch to nightly
    shell: |
      {{home_dir}}/.cargo/bin/rustup default nightly
    args:
      executable: /bin/bash
