# # NOTE: These instructions only work for 64-bit Debian-based
# # Linux distributions such as Ubuntu, Mint etc.

# # 1. Install our official public software signing key:
# wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg;
# cat signal-desktop-keyring.gpg | sudo tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null

# # 2. Add our repository to your list of repositories:
# wget -O signal-desktop.sources https://updates.signal.org/static/desktop/apt/signal-desktop.sources;
# cat signal-desktop.sources | sudo tee /etc/apt/sources.list.d/signal-desktop.sources > /dev/null

# # 3. Update your package database and install Signal:
# sudo apt update && sudo apt install signal-desktop
- hosts: all
  become: true
  connection: local
  tasks:
  - name: add the Signal GPG keys
    ansible.builtin.deb822_repository:
      name: Signal
      types: deb
      uris: https://updates.signal.org/desktop/apt
      suites: xenial
      components:
      - main
      signed_by: https://updates.signal.org/desktop/apt/keys.asc
  
  - name: install signal-desktop
    package:
      name: signal-desktop
      state: latest