---
# Deploy/update a personal computer system.
- hosts: localhost
  connection: local
  tasks: []

- import_playbook: config.yml
- import_playbook: apt.yml
- import_playbook: udev.yml

- import_playbook: packages.yml
- import_playbook: yubico.yml

- import_playbook: firefox.yml
- import_playbook: syncthing.yml
- import_playbook: vscode.yml
- import_playbook: podman.yml
- import_playbook: docker-compose.yml
- import_playbook: podman-desktop.yml
- import_playbook: pyenv.yml

- import_playbook: golang.yml
- import_playbook: jetbrains.yml
- import_playbook: freecad.yml
- import_playbook: rust.yml

- import_playbook: bwrap.yml

- import_playbook: clang.yml

- import_playbook: libvirt.yml

#- import_playbook: opensnitch.yml

# Support CLI tools
- import_playbook: awscli.yml
- import_playbook: kubectl.yml
- import_playbook: stern.yml
- import_playbook: helm.yml
- import_playbook: github-cli.yml
- import_playbook: minikube.yml
- import_playbook: minio.yml
- import_playbook: rclone.yml
- import_playbook: awless.yml
- import_playbook: terraform.yml
- import_playbook: restic.yml
- import_playbook: bazelisk.yml
- import_playbook: envoy.yml
- import_playbook: grpccurl.yml
- import_playbook: logcli.yml
- import_playbook: atuin.yml
- import_playbook: dagger.yml
- import_playbook: go-jira.yml
- import_playbook: caddy.yml
- import_playbook: bfg.yml


- import_playbook: ca-certificates-tweaks.yml

# TODO: figure out how to pull the desktop config
# TODO: auto-setup Firefox profiles
- import_playbook: gtk-themes.yml
- import_playbook: dconf-restore.yml
- import_playbook: user.yml