# X2Go server - only imported by site.yml when x2go_server is true.
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Add x2go PPA
    apt_repository:
      repo: 'ppa:x2go/stable'

  - name: Install the x2go server
    package:
      name:
      - x2goserver
      - x2goserver-xsession
