files_dir: "{{playbook_dir}}/files"

home_dir: "{{ lookup('env', 'HOME') }}"

user_dirs:
  opt: "{{ home_dir }}/opt"
  downloads: "{{ home_dir }}/Downloads"
  bin: "{{ home_dir }}/bin"

persistent_user_config: 
  linux:
    shared: "{{ home_dir }}/config/linux/shared"
  windows:
    shared: "{{ home_dir }}/config/windows/shared"
  shared:
    "{{ home_dir }}/config/shared"

apt_keyring_dir: /etc/apt/keyrings

network:
  vm_network: 192.168.122.1/24
